In [897]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import tree
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score

from sklearn.datasets import load_iris

from collections import Counter

import random

In [898]:
data = pd.read_csv('train.csv')
data1 = pd.read_csv('test.csv')

In [899]:
x = data.drop('Transported', axis = 1)
y = (data['Transported'] == 1).astype('int8')

In [900]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [901]:
x_train = pd.get_dummies(x_train, columns = ["HomePlanet"], dtype = "int8")

In [902]:
x_test = pd.get_dummies(x_test, columns = ["HomePlanet"], dtype = "int8")

In [903]:
data1

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,9266_02,Earth,True,G/1496/S,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0,Jeron Peter
4273,9269_01,Earth,False,NaN,TRAPPIST-1e,42.0,False,0.0,847.0,17.0,10.0,144.0,Matty Scheron
4274,9271_01,Mars,True,D/296/P,55 Cancri e,NaN,False,0.0,0.0,0.0,0.0,0.0,Jayrin Pore
4275,9273_01,Europa,False,D/297/P,NaN,NaN,False,0.0,2680.0,0.0,0.0,523.0,Kitakan Conale
4276,9277_01,Earth,True,G/1498/S,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0,Lilace Leonzaley

In [904]:
x_test

,PassengerId,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars
825,0878_01,False,D/31/S,PSO J318.5-22,37.0,True,381.0,0.0,3.0,447.0,0.0,Sceres Bancy,0,0,1
6960,7395_01,True,B/277/S,55 Cancri e,17.0,False,0.0,0.0,0.0,0.0,0.0,Schelik Suasharic,0,1,0
7181,7669_01,False,G/1230/P,TRAPPIST-1e,24.0,False,NaN,636.0,136.0,37.0,0.0,Philda Whiters,1,0,0
8565,9148_01,False,G/1473/S,TRAPPIST-1e,11.0,False,0.0,0.0,0.0,0.0,0.0,Elice Paulllegory,1,0,0
6443,6802_01,False,A/68/P,55 Cancri e,42.0,False,1751.0,516.0,0.0,12.0,672.0,Eleb Disteady,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1608,1709_01,False,F/326/S,TRAPPIST-1e,23.0,False,31.0,0.0,1247.0,0.0,47.0,Jurbet Minen,0,0,1
3521,3777_01,True,B/147/S,55 Cancri e,35.0,False,0.0,0.0,0.0,0.0,0.0,Mareson Clunic,0,1,0
4883,5206_03,False,G/841/P,PSO J318.5-22,48.0,False,0.0,2.0,72.0,554.0,143.0,Ericia Briggston,1,0,0
1439,1521_01,True,F/295/S,TRAPPIST-1e,28.0,False,0.0,0.0,0.0,0.0,0.0,Repart FlitÃ©,0,0,1
6062,6407_01,True,G/1033/P,TRAPPIST-1e,19.0,False,0.0,0.0,0.0,0.0,0.0,NaN,1,0,0

In [905]:
x_train['CryoSleep'] = (x_train['CryoSleep'] == 1).astype('int8')

In [906]:
x_test['CryoSleep'] = (x_test['CryoSleep'] == 1).astype('int8')

In [907]:
x_train

,PassengerId,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars
2991,3236_03,0,E/200/P,TRAPPIST-1e,18.0,False,0.0,30.0,0.0,756.0,5.0,Anton Woody,1,0,0
4407,4679_01,0,C/181/S,TRAPPIST-1e,63.0,False,0.0,4579.0,1.0,1006.0,2084.0,Zaviton Iniouser,0,1,0
3024,3279_01,0,C/123/S,55 Cancri e,9.0,False,0.0,0.0,0.0,0.0,0.0,Mard Whifounrew,0,1,0
743,0781_01,0,G/118/S,PSO J318.5-22,21.0,False,14.0,33.0,0.0,3.0,467.0,Diandy Valexandez,1,0,0
1725,1833_01,0,C/61/P,55 Cancri e,48.0,False,140.0,127.0,0.0,4102.0,521.0,Mirark Scoudelle,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6873,7274_01,0,F/1506/P,TRAPPIST-1e,13.0,False,305.0,582.0,12.0,19.0,0.0,Loria Woodwinton,1,0,0
7593,8118_01,1,G/1310/P,TRAPPIST-1e,21.0,False,0.0,0.0,0.0,0.0,0.0,Eilace Browlerson,1,0,0
5745,6092_02,1,G/991/S,PSO J318.5-22,7.0,False,0.0,0.0,0.0,0.0,0.0,Antony Singtons,1,0,0
7245,7747_01,0,F/1611/P,TRAPPIST-1e,41.0,False,688.0,31.0,1880.0,0.0,NaN,Supix Dal,0,0,1
3144,3392_02,1,G/541/S,TRAPPIST-1e,4.0,False,0.0,0.0,0.0,0.0,0.0,Jenn Gallard,1,0,0

In [908]:
x_test

,PassengerId,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars
825,0878_01,0,D/31/S,PSO J318.5-22,37.0,True,381.0,0.0,3.0,447.0,0.0,Sceres Bancy,0,0,1
6960,7395_01,1,B/277/S,55 Cancri e,17.0,False,0.0,0.0,0.0,0.0,0.0,Schelik Suasharic,0,1,0
7181,7669_01,0,G/1230/P,TRAPPIST-1e,24.0,False,NaN,636.0,136.0,37.0,0.0,Philda Whiters,1,0,0
8565,9148_01,0,G/1473/S,TRAPPIST-1e,11.0,False,0.0,0.0,0.0,0.0,0.0,Elice Paulllegory,1,0,0
6443,6802_01,0,A/68/P,55 Cancri e,42.0,False,1751.0,516.0,0.0,12.0,672.0,Eleb Disteady,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1608,1709_01,0,F/326/S,TRAPPIST-1e,23.0,False,31.0,0.0,1247.0,0.0,47.0,Jurbet Minen,0,0,1
3521,3777_01,1,B/147/S,55 Cancri e,35.0,False,0.0,0.0,0.0,0.0,0.0,Mareson Clunic,0,1,0
4883,5206_03,0,G/841/P,PSO J318.5-22,48.0,False,0.0,2.0,72.0,554.0,143.0,Ericia Briggston,1,0,0
1439,1521_01,1,F/295/S,TRAPPIST-1e,28.0,False,0.0,0.0,0.0,0.0,0.0,Repart FlitÃ©,0,0,1
6062,6407_01,1,G/1033/P,TRAPPIST-1e,19.0,False,0.0,0.0,0.0,0.0,0.0,NaN,1,0,0

In [909]:
vals = ['True', 'False']
probs = [x_train['VIP'].value_counts()[0]/len(x_train), x_train['VIP'].value_counts()[1]/len(x_train)]

vals1 = ['TRAPPIST-1e', '55 Cancri e', 'PSO J318.5-22']
probs1 = [x_train['Destination'].value_counts().iloc[0]/len(x_train), 
          x_train['Destination'].value_counts().iloc[1]/len(x_train), 
          x_train['Destination'].value_counts().iloc[2]/len(x_train)]

C:\Users\hacat\AppData\Local\Temp\ipykernel_6648\1590930914.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  probs = [x_train['VIP'].value_counts()[0]/len(x_train), x_train['VIP'].value_counts()[1]/len(x_train)]
C:\Users\hacat\AppData\Local\Temp\ipykernel_6648\1590930914.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  probs = [x_train['VIP'].value_counts()[0]/len(x_train), x_train['VIP'].value_counts()[1]/len(x_train)]

In [910]:
vals = ['True', 'False']
probs = [x_test['VIP'].value_counts()[0]/len(x_test), x_test['VIP'].value_counts()[1]/len(x_test)]

vals1 = ['TRAPPIST-1e', '55 Cancri e', 'PSO J318.5-22']
probs1 = [x_test['Destination'].value_counts().iloc[0]/len(x_test), 
          x_test['Destination'].value_counts().iloc[1]/len(x_test), 
          x_test['Destination'].value_counts().iloc[2]/len(x_test)]

C:\Users\hacat\AppData\Local\Temp\ipykernel_6648\2295634326.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  probs = [x_test['VIP'].value_counts()[0]/len(x_test), x_test['VIP'].value_counts()[1]/len(x_test)]
C:\Users\hacat\AppData\Local\Temp\ipykernel_6648\2295634326.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  probs = [x_test['VIP'].value_counts()[0]/len(x_test), x_test['VIP'].value_counts()[1]/len(x_test)]

In [911]:
x_train = x_train.dropna(subset=['Cabin'])

In [912]:
x_test = x_test.dropna(subset=['Cabin'])

In [913]:
(x_train['RoomService'].isna()).sum()

np.int64(123)

In [914]:
(x_test['RoomService'].isna()).sum()

np.int64(54)

In [915]:
x_train['VIP'] = x_train['VIP'].fillna(random.choices(vals, weights=probs, k=1)[0])

C:\Users\hacat\AppData\Local\Temp\ipykernel_6648\3707066986.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train['VIP'] = x_train['VIP'].fillna(random.choices(vals, weights=probs, k=1)[0])

In [916]:
x_test['VIP'] = x_test['VIP'].fillna(random.choices(vals, weights=probs, k=1)[0])

C:\Users\hacat\AppData\Local\Temp\ipykernel_6648\2523777886.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test['VIP'] = x_test['VIP'].fillna(random.choices(vals, weights=probs, k=1)[0])

In [917]:
x_train['VIP'] = (x_train['VIP'] != False).astype('int8')

C:\Users\hacat\AppData\Local\Temp\ipykernel_6648\540629861.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train['VIP'] = (x_train['VIP'] != False).astype('int8')

In [918]:
x_test['VIP'] = (x_test['VIP'] != False).astype('int8')

C:\Users\hacat\AppData\Local\Temp\ipykernel_6648\2058982954.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test['VIP'] = (x_test['VIP'] != False).astype('int8')

In [919]:
x_train['VIP'].value_counts()

VIP
0    5674
1     269
Name: count, dtype: int64

In [920]:
x_test['VIP'].value_counts()

VIP
0    2430
1     121
Name: count, dtype: int64

In [921]:
x_train = x_train.drop('Name', axis = 1)

In [922]:
x_test = x_test.drop('Name', axis = 1)

In [923]:
x_train

,PassengerId,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars
2991,3236_03,0,E/200/P,TRAPPIST-1e,18.0,0,0.0,30.0,0.0,756.0,5.0,1,0,0
4407,4679_01,0,C/181/S,TRAPPIST-1e,63.0,0,0.0,4579.0,1.0,1006.0,2084.0,0,1,0
3024,3279_01,0,C/123/S,55 Cancri e,9.0,0,0.0,0.0,0.0,0.0,0.0,0,1,0
743,0781_01,0,G/118/S,PSO J318.5-22,21.0,0,14.0,33.0,0.0,3.0,467.0,1,0,0
1725,1833_01,0,C/61/P,55 Cancri e,48.0,0,140.0,127.0,0.0,4102.0,521.0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6873,7274_01,0,F/1506/P,TRAPPIST-1e,13.0,0,305.0,582.0,12.0,19.0,0.0,1,0,0
7593,8118_01,1,G/1310/P,TRAPPIST-1e,21.0,0,0.0,0.0,0.0,0.0,0.0,1,0,0
5745,6092_02,1,G/991/S,PSO J318.5-22,7.0,0,0.0,0.0,0.0,0.0,0.0,1,0,0
7245,7747_01,0,F/1611/P,TRAPPIST-1e,41.0,0,688.0,31.0,1880.0,0.0,NaN,0,0,1
3144,3392_02,1,G/541/S,TRAPPIST-1e,4.0,0,0.0,0.0,0.0,0.0,0.0,1,0,0

In [924]:
x_test

,PassengerId,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars
825,0878_01,0,D/31/S,PSO J318.5-22,37.0,1,381.0,0.0,3.0,447.0,0.0,0,0,1
6960,7395_01,1,B/277/S,55 Cancri e,17.0,0,0.0,0.0,0.0,0.0,0.0,0,1,0
7181,7669_01,0,G/1230/P,TRAPPIST-1e,24.0,0,NaN,636.0,136.0,37.0,0.0,1,0,0
8565,9148_01,0,G/1473/S,TRAPPIST-1e,11.0,0,0.0,0.0,0.0,0.0,0.0,1,0,0
6443,6802_01,0,A/68/P,55 Cancri e,42.0,0,1751.0,516.0,0.0,12.0,672.0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1608,1709_01,0,F/326/S,TRAPPIST-1e,23.0,0,31.0,0.0,1247.0,0.0,47.0,0,0,1
3521,3777_01,1,B/147/S,55 Cancri e,35.0,0,0.0,0.0,0.0,0.0,0.0,0,1,0
4883,5206_03,0,G/841/P,PSO J318.5-22,48.0,0,0.0,2.0,72.0,554.0,143.0,1,0,0
1439,1521_01,1,F/295/S,TRAPPIST-1e,28.0,0,0.0,0.0,0.0,0.0,0.0,0,0,1
6062,6407_01,1,G/1033/P,TRAPPIST-1e,19.0,0,0.0,0.0,0.0,0.0,0.0,1,0,0

In [925]:
x_train['Destination'].value_counts()

Destination
TRAPPIST-1e      4075
55 Cancri e      1209
PSO J318.5-22     532
Name: count, dtype: int64

In [926]:
x_test['Destination'].value_counts()

Destination
TRAPPIST-1e      1713
55 Cancri e       541
PSO J318.5-22     246
Name: count, dtype: int64

In [927]:
x_train['Destination'] = x_train['Destination'].fillna(random.choices(vals1, weights=probs1, k=1)[0])

In [928]:
x_test['Destination'] = x_test['Destination'].fillna(random.choices(vals1, weights=probs1, k=1)[0])

In [929]:
x_train['Destination'].value_counts()

Destination
TRAPPIST-1e      4075
55 Cancri e      1336
PSO J318.5-22     532
Name: count, dtype: int64

In [930]:
x_test['Destination'].value_counts()

Destination
TRAPPIST-1e      1764
55 Cancri e       541
PSO J318.5-22     246
Name: count, dtype: int64

In [931]:
x_train['Age'] = x_train['Age'].fillna(x_train['Age'].mean())

In [932]:
x_test['Age'] = x_test['Age'].fillna(x_test['Age'].mean())

In [933]:
x_train['RoomService'] = x_train['RoomService'].fillna(0)
x_train['FoodCourt'] = x_train['FoodCourt'].fillna(0)
x_train['ShoppingMall'] = x_train['ShoppingMall'].fillna(0)
x_train['Spa'] = x_train['Spa'].fillna(0)
x_train['VRDeck'] = x_train['VRDeck'].fillna(0)

In [934]:
x_test['RoomService'] = x_test['RoomService'].fillna(0)
x_test['FoodCourt'] = x_test['FoodCourt'].fillna(0)
x_test['ShoppingMall'] = x_test['ShoppingMall'].fillna(0)
x_test['Spa'] = x_test['Spa'].fillna(0)
x_test['VRDeck'] = x_test['VRDeck'].fillna(0)

In [935]:
x_test

,PassengerId,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars
825,0878_01,0,D/31/S,PSO J318.5-22,37.0,1,381.0,0.0,3.0,447.0,0.0,0,0,1
6960,7395_01,1,B/277/S,55 Cancri e,17.0,0,0.0,0.0,0.0,0.0,0.0,0,1,0
7181,7669_01,0,G/1230/P,TRAPPIST-1e,24.0,0,0.0,636.0,136.0,37.0,0.0,1,0,0
8565,9148_01,0,G/1473/S,TRAPPIST-1e,11.0,0,0.0,0.0,0.0,0.0,0.0,1,0,0
6443,6802_01,0,A/68/P,55 Cancri e,42.0,0,1751.0,516.0,0.0,12.0,672.0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1608,1709_01,0,F/326/S,TRAPPIST-1e,23.0,0,31.0,0.0,1247.0,0.0,47.0,0,0,1
3521,3777_01,1,B/147/S,55 Cancri e,35.0,0,0.0,0.0,0.0,0.0,0.0,0,1,0
4883,5206_03,0,G/841/P,PSO J318.5-22,48.0,0,0.0,2.0,72.0,554.0,143.0,1,0,0
1439,1521_01,1,F/295/S,TRAPPIST-1e,28.0,0,0.0,0.0,0.0,0.0,0.0,0,0,1
6062,6407_01,1,G/1033/P,TRAPPIST-1e,19.0,0,0.0,0.0,0.0,0.0,0.0,1,0,0

In [936]:
x_train

,PassengerId,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars
2991,3236_03,0,E/200/P,TRAPPIST-1e,18.0,0,0.0,30.0,0.0,756.0,5.0,1,0,0
4407,4679_01,0,C/181/S,TRAPPIST-1e,63.0,0,0.0,4579.0,1.0,1006.0,2084.0,0,1,0
3024,3279_01,0,C/123/S,55 Cancri e,9.0,0,0.0,0.0,0.0,0.0,0.0,0,1,0
743,0781_01,0,G/118/S,PSO J318.5-22,21.0,0,14.0,33.0,0.0,3.0,467.0,1,0,0
1725,1833_01,0,C/61/P,55 Cancri e,48.0,0,140.0,127.0,0.0,4102.0,521.0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6873,7274_01,0,F/1506/P,TRAPPIST-1e,13.0,0,305.0,582.0,12.0,19.0,0.0,1,0,0
7593,8118_01,1,G/1310/P,TRAPPIST-1e,21.0,0,0.0,0.0,0.0,0.0,0.0,1,0,0
5745,6092_02,1,G/991/S,PSO J318.5-22,7.0,0,0.0,0.0,0.0,0.0,0.0,1,0,0
7245,7747_01,0,F/1611/P,TRAPPIST-1e,41.0,0,688.0,31.0,1880.0,0.0,0.0,0,0,1
3144,3392_02,1,G/541/S,TRAPPIST-1e,4.0,0,0.0,0.0,0.0,0.0,0.0,1,0,0

In [937]:
y_train = y_train.loc[x_train.index]

In [938]:
y_test = y_test.loc[x_test.index]

In [939]:
y_train

2991    0
4407    1
3024    1
743     0
1725    0
       ..
6873    0
7593    0
5745    1
7245    0
3144    1
Name: Transported, Length: 5943, dtype: int8

In [940]:
y_test

825     0
6960    1
7181    0
8565    0
6443    0
       ..
1608    0
3521    1
4883    0
1439    1
6062    1
Name: Transported, Length: 2551, dtype: int8

In [941]:
x_train[['Deck', 'Num', 'Side']] = x_train['Cabin'].str.split('/', expand=True)

In [942]:
x_test[['Deck', 'Num', 'Side']] = x_test['Cabin'].str.split('/', expand=True)

In [943]:
x_train['Side'] = (x_train['Side'] == 'S').astype('int8')

In [944]:
x_test['Side'] = (x_test['Side'] == 'S').astype('int8')

In [945]:
x_train = x_train.drop('Cabin', axis = 1)

In [946]:
x_test = x_test.drop('Cabin', axis = 1)

In [947]:
x_train

,PassengerId,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,Deck,Num,Side
2991,3236_03,0,TRAPPIST-1e,18.0,0,0.0,30.0,0.0,756.0,5.0,1,0,0,E,200,0
4407,4679_01,0,TRAPPIST-1e,63.0,0,0.0,4579.0,1.0,1006.0,2084.0,0,1,0,C,181,1
3024,3279_01,0,55 Cancri e,9.0,0,0.0,0.0,0.0,0.0,0.0,0,1,0,C,123,1
743,0781_01,0,PSO J318.5-22,21.0,0,14.0,33.0,0.0,3.0,467.0,1,0,0,G,118,1
1725,1833_01,0,55 Cancri e,48.0,0,140.0,127.0,0.0,4102.0,521.0,0,1,0,C,61,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6873,7274_01,0,TRAPPIST-1e,13.0,0,305.0,582.0,12.0,19.0,0.0,1,0,0,F,1506,0
7593,8118_01,1,TRAPPIST-1e,21.0,0,0.0,0.0,0.0,0.0,0.0,1,0,0,G,1310,0
5745,6092_02,1,PSO J318.5-22,7.0,0,0.0,0.0,0.0,0.0,0.0,1,0,0,G,991,1
7245,7747_01,0,TRAPPIST-1e,41.0,0,688.0,31.0,1880.0,0.0,0.0,0,0,1,F,1611,0
3144,3392_02,1,TRAPPIST-1e,4.0,0,0.0,0.0,0.0,0.0,0.0,1,0,0,G,541,1

In [948]:
x_test

,PassengerId,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,Deck,Num,Side
825,0878_01,0,PSO J318.5-22,37.0,1,381.0,0.0,3.0,447.0,0.0,0,0,1,D,31,1
6960,7395_01,1,55 Cancri e,17.0,0,0.0,0.0,0.0,0.0,0.0,0,1,0,B,277,1
7181,7669_01,0,TRAPPIST-1e,24.0,0,0.0,636.0,136.0,37.0,0.0,1,0,0,G,1230,0
8565,9148_01,0,TRAPPIST-1e,11.0,0,0.0,0.0,0.0,0.0,0.0,1,0,0,G,1473,1
6443,6802_01,0,55 Cancri e,42.0,0,1751.0,516.0,0.0,12.0,672.0,0,1,0,A,68,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1608,1709_01,0,TRAPPIST-1e,23.0,0,31.0,0.0,1247.0,0.0,47.0,0,0,1,F,326,1
3521,3777_01,1,55 Cancri e,35.0,0,0.0,0.0,0.0,0.0,0.0,0,1,0,B,147,1
4883,5206_03,0,PSO J318.5-22,48.0,0,0.0,2.0,72.0,554.0,143.0,1,0,0,G,841,0
1439,1521_01,1,TRAPPIST-1e,28.0,0,0.0,0.0,0.0,0.0,0.0,0,0,1,F,295,1
6062,6407_01,1,TRAPPIST-1e,19.0,0,0.0,0.0,0.0,0.0,0.0,1,0,0,G,1033,0

In [949]:
x_train = pd.get_dummies(x_train, columns = ["Deck"], dtype = "int8")

In [950]:
x_test = pd.get_dummies(x_test, columns = ["Deck"], dtype = "int8")

In [951]:
x_train

,PassengerId,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,...,Num,Side,Deck_A,Deck_B,Deck_C,Deck_D,Deck_E,Deck_F,Deck_G,Deck_T
2991,3236_03,0,TRAPPIST-1e,18.0,0,0.0,30.0,0.0,756.0,5.0,...,200,0,0,0,0,0,1,0,0,0
4407,4679_01,0,TRAPPIST-1e,63.0,0,0.0,4579.0,1.0,1006.0,2084.0,...,181,1,0,0,1,0,0,0,0,0
3024,3279_01,0,55 Cancri e,9.0,0,0.0,0.0,0.0,0.0,0.0,...,123,1,0,0,1,0,0,0,0,0
743,0781_01,0,PSO J318.5-22,21.0,0,14.0,33.0,0.0,3.0,467.0,...,118,1,0,0,0,0,0,0,1,0
1725,1833_01,0,55 Cancri e,48.0,0,140.0,127.0,0.0,4102.0,521.0,...,61,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6873,7274_01,0,TRAPPIST-1e,13.0,0,305.0,582.0,12.0,19.0,0.0,...,1506,0,0,0,0,0,0,1,0,0
7593,8118_01,1,TRAPPIST-1e,21.0,0,0.0,0.0,0.0,0.0,0.0,...,1310,0,0,0,0,0,0,0,1,0
5745,6092_02,1,PSO J318.5-22,7.0,0,0.0,0.0,0.0,0.0,0.0,...,991,1,0,0,0,0,0,0,1,0
7245,7747_01,0,TRAPPIST-1e,41.0,0,688.0,31.0,1880.0,0.0,0.0,...,1611,0,0,0,0,0,0,1,0,0
3144,3392_02,1,TRAPPIST-1e,4.0,0,0.0,0.0,0.0,0.0,0.0,...,541,1,0,0,0,0,0,0,1,0

In [952]:
x_test

,PassengerId,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,...,Num,Side,Deck_A,Deck_B,Deck_C,Deck_D,Deck_E,Deck_F,Deck_G,Deck_T
825,0878_01,0,PSO J318.5-22,37.0,1,381.0,0.0,3.0,447.0,0.0,...,31,1,0,0,0,1,0,0,0,0
6960,7395_01,1,55 Cancri e,17.0,0,0.0,0.0,0.0,0.0,0.0,...,277,1,0,1,0,0,0,0,0,0
7181,7669_01,0,TRAPPIST-1e,24.0,0,0.0,636.0,136.0,37.0,0.0,...,1230,0,0,0,0,0,0,0,1,0
8565,9148_01,0,TRAPPIST-1e,11.0,0,0.0,0.0,0.0,0.0,0.0,...,1473,1,0,0,0,0,0,0,1,0
6443,6802_01,0,55 Cancri e,42.0,0,1751.0,516.0,0.0,12.0,672.0,...,68,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1608,1709_01,0,TRAPPIST-1e,23.0,0,31.0,0.0,1247.0,0.0,47.0,...,326,1,0,0,0,0,0,1,0,0
3521,3777_01,1,55 Cancri e,35.0,0,0.0,0.0,0.0,0.0,0.0,...,147,1,0,1,0,0,0,0,0,0
4883,5206_03,0,PSO J318.5-22,48.0,0,0.0,2.0,72.0,554.0,143.0,...,841,0,0,0,0,0,0,0,1,0
1439,1521_01,1,TRAPPIST-1e,28.0,0,0.0,0.0,0.0,0.0,0.0,...,295,1,0,0,0,0,0,1,0,0
6062,6407_01,1,TRAPPIST-1e,19.0,0,0.0,0.0,0.0,0.0,0.0,...,1033,0,0,0,0,0,0,0,1,0

In [953]:
x_test = pd.get_dummies(x_test, columns = ["Destination"], dtype = "int8")

In [954]:
x_train = pd.get_dummies(x_train, columns = ["Destination"], dtype = "int8")

In [955]:
clf = DecisionTreeClassifier(max_depth=3, min_samples_split=2, min_samples_leaf=1, criterion='gini')

clf.fit(x_train, y_train)

print('Test accuracy:', accuracy_score(y_test, clf.predict(x_test)))
print('Train accuracy:', accuracy_score(y_train, clf.predict(x_train)))

Test accuracy: 0.7122696981575852
Train accuracy: 0.7198384654215043

In [956]:
y_test = clf.predict(x_test)

In [957]:
y_test

array([0, 1, 0, ..., 0, 1, 1], shape=(2551,), dtype=int8)